name: Test Case Template
description: This template helps with writing test cases with predefined steps and expectations.
labels: ["Test Case", "QAReview"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Important Notice**  
        - The **Test Execution Results** and **Expected Results** should **only** be marked by the tester who executes the test case.  
        - Ensure all steps are clearly defined before execution.

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: "List any preconditions that must be met before executing this test case."
      placeholder: "E.g., User must be logged in, feature must be enabled."

  - type: checkboxes
    id: os-to-be-tested
    attributes:
      label: OS to be tested on
      description: "Select one or more operating systems to test on."
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: "Other"
    validations:
      required: true

  - type: input
    id: custom-os
    attributes:
      label: Other OS (if selected above)
      description: "If 'Other' is selected, specify the operating system."
      placeholder: "Enter custom OS"

  - type: checkboxes
    id: cross-os
    attributes:
      label: Cross-OS Testing
      description: "Check if the test should be executed on multiple operating systems."
      options:
        - label: "Cross-OS testing is required"

  - type: input
    id: device-or-devices
    attributes:
      label: Device or Devices
      description: "Specify the device(s) for testing (e.g., iPhone 12, Samsung Galaxy S21, MacBook Pro)."
      placeholder: "E.g., iPhone 12, MacBook Pro"

  - type: checkboxes
    id: browser-or-browsers
    attributes:
      label: Browser or Browsers
      description: "Select one or more browsers to test on."
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Opera
        - label: "Other"
    validations:
      required: true

  - type: input
    id: custom-browser
    attributes:
      label: Other Browser (if selected above)
      description: "If 'Other' is selected, specify the browser."
      placeholder: "Enter custom browser"

  - type: checkboxes
    id: cross-browser
    attributes:
      label: Cross-Browser Testing
      description: "Check if the test should be executed across multiple browsers."
      options:
        - label: "Cross-browser testing is required"

  - type: textarea
    id: test-steps
    attributes:
      label: Test Steps
      description: "Write out the steps required to execute the test case."
      placeholder: |
        **Step 1:**
        - Write here step 1
        - [ ] **Expected Results:** *(To be marked by the tester)*
        - Write here expected results for Step 1
        
        **Step 2:**
        - Write here step 2
        - [ ] **Expected Results:** *(To be marked by the tester)*
        - Write here expected results for Step 2
        
        **Step 3:**
        - Write here step 3
        - [ ] **Expected Results:** *(To be marked by the tester)*
        - Write here expected results for Step 3
        
        <!-- Add more steps as needed following the same format. -->

  - type: checkboxes
    id: test-results
    attributes:
      label: Test Execution Results
      description: "Indicate whether the expected results passed, failed, or partially passed. *(To be marked by the tester who executes the test case.)*"
      options:
        - label: "All expected results have passed"
        - label: "Some expected results have passed"
        - label: "All expected results have failed"
    validations:
      required: true
