name: Auto Label Test Cases

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  auto-label-test-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const body = issue.body || "";
            const labels = issue.labels.map(label => label.name);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = issue.number;

            const labelsToAdd = [];
            const labelsToRemove = [];

            if (!labels.includes("Test Case")) return;

            const getDropdownValue = (label) => {
              const regex = new RegExp(`${label}\\s*\\n([^\\n]+)(\\n|$)`, 'i');
              const match = body.match(regex);
              return match ? match[1].trim() : null;
            };

            const isCheckboxChecked = (label) => {
              const regex = new RegExp(`- \\[x\\]\\s*${label}`, 'i');
              return regex.test(body);
            };

            const handleLabels = (selected, options) => {
              options.forEach(option => {
                if (selected === option && !labels.includes(option)) labelsToAdd.push(option);
                if (selected !== option && labels.includes(option)) labelsToRemove.push(option);
              });
            };

            handleLabels(getDropdownValue("Type of Testing"), [
              "Navigation", "Content Testing", "GUI and Usability",
              "Performance testing", "Compatibility Testing"
            ]);

            const contextValue = getDropdownValue("Where is this test run\\?");
            handleLabels(contextValue, ["local", "production"]);

            handleLabels(getDropdownValue("Section of the Website"), [
              "Header", "Misiunea Noastra", "Cum poti ajuta si tu?",
              "De ce sa ajuti?", "Echipa", "Povesti de succes", "Footer"
            ]);

            const handleCheckboxLabel = (checkboxLabel, gitHubLabel) => {
              if (isCheckboxChecked(checkboxLabel) && !labels.includes(gitHubLabel)) labelsToAdd.push(gitHubLabel);
              if (!isCheckboxChecked(checkboxLabel) && labels.includes(gitHubLabel)) labelsToRemove.push(gitHubLabel);
            };

            handleCheckboxLabel("Cross-browser testing is required", "Cross-browser");
            handleCheckboxLabel("Cross-OS testing is required", "Cross-OS");

            const bugFoundChecked = isCheckboxChecked("Bug was discovered during test execution");
            if (bugFoundChecked && !labels.includes("Bug(s) found")) {
              labelsToAdd.push("Bug(s) found");
            } else if (!bugFoundChecked && labels.includes("Bug(s) found")) {
              labelsToRemove.push("Bug(s) found");
            }

            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({owner, repo, issue_number, labels: labelsToAdd});
            }

            for (const label of labelsToRemove) {
              await github.rest.issues.removeLabel({owner, repo, issue_number, name: label}).catch(() => {});
            }
